DON/DON/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app'))
]

DON/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.index,name='index'), # 首页
    url(r'^login/$',views.login,name='login'), # 注册
    url(r'^outlogin/$',views.outlogin,name='outlogin'), # 退出登录
    url(r'^onload/$',views.onload,name='onload'), # 登录
    url(r'^shoplist/$',views.shoplist,name='shoplist'), # 商品展示
    url(r'^shopinfo/(\d+)/$',views.shopinfo,name='shopinfo'), # 商品详情页
    url(r'^MyCar/$',views.MyCar,name='MyCar'), # 购物车
    url(r'^addCar/$',views.addCar,name='addCar'), # 添加购物车
    url(r'^subCar/$',views.subCar,name='subCar'), # 删除购物车
    url(r'^statusCar/$',views.statusCar,name='statusCar'), #
    url(r'^isallCar/$',views.isallCar,name='isallCar'),
    url(r'^addshop/$',views.addshop,name='addshop'),
    url(r'^subshop/$',views.subshop,name='subshop'),
    url(r'^checkphone/$',views.checkphone,name='checkphone'),
    url(r'^removeshop/$',views.removeshop,name='removeshop'),
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    url(r'^orderdetail/(\d+)/$',views.orderdetail,name='orderdetail'),
    url(r'^orderlist/(\d+)/$',views.orderlist,name='orderlist'),
]

DON/templates/onload/onload.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/onload.css' %}"/>


    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/onload.js' %}"></script>
    {#        <script src="{% static 'js/jiaoben.js' %}"></script>#}
</head>
<body>

<div class="topbar">
    <div class="topbarleft">
        <p>
					<span id="hello">
						您好,欢迎光临戴欧妮珠宝网！
                        <!--<a href="onload.html">登陆</a> /
                        <a href="login.html">注册</a>-->
					</span>
            <span>体验中心：<a href="#">深圳分店</a></span>
            <span class="chang">切换</span>
        </p>
    </div>
    <div class="topbarright">
        <a href="{% url 'app:MyCar' %}">
					<span>
						<img src="{% static 'img/banicon.png' %}" class="img">
					            我的戴欧妮
					</span>
        </a>
        <a href="#">
					<span>
						我的珠宝箱[<span class="zero zero1">0</span>]
					</span>
        </a>
        <a href="#">
					<span>
						&lt;
					             正品认证
					</span>
        </a>
        <a href="#">
					<span>
						&lt;
					    <span class="zero">进店预约</span>
					</span>
        </a>
        <a href="#">
					<span>
						<img src="{% static 'img/banicon2.png' %}">
					            手机版
					</span>
        </a>
        <a href="#">
					<span>
						<img src="{% static 'img/banicon3.png' %}">
					             微信
					</span>
        </a>
        <a href="#">
					<span>
						<img src="{% static 'img/banicon4.png' %}">
					             微博
					</span>
        </a>
    </div>
</div>
<div class="change">
    <p>切换体验中心<span>×</span></p>
    <div class="changeonee">
        <!--<div class="changeone">
            <p>华北：</p>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
        </div>
        <div class="changeone">
            <p>华北：</p>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
            <span>北京·戴欧妮旗舰店</span>
        </div>-->
    </div>
</div>
<div class="header">
    <div class="headerleft">
        <img src="{% static 'img/dionly.png' %}">
    </div>
    <div class="headermain">
        <p class="p1">
            <input type="text" placeholder="请输入型号或名称">
            <input type="button" value="搜索">
        </p>
        <p class="p2">
					<span>
						永恒
					</span>
            <span>
						浪漫
					</span>
            <span>
						一生
					</span>
            <span>
						爱情
					</span>
            <span>
						密语
					</span>
        </p>
    </div>
    <div class="headerright">
        <img src="{% static 'img/二维码.png' %}">
    </div>
</div>
<div class="menuer">
    <div class="menuerleft">
				<span class="one">
					所有分类
				</span>
        <span class="unhover">

				</span>
    </div>
    <div class="menuermain">
        <a href="{% url 'app:index' %}">
					<span>
						首页
					</span>
        </a>
        <a href="#">
					<span>
						裸钻
					</span>
        </a>
        <a href="#">
					<span>
						钻戒定制
					</span>
        </a>
        <a href="#">
					<span>
						定价产品
					</span>
        </a>
        <a href="#">
					<span>
						黄金
					</span>
        </a>
        <a href="#">
					<span>
						高端定制
					</span>
        </a>
        <a href="#">
					<span>
						优惠活动
					</span>
        </a>
        <a href="#">
					<span>
						珠宝百科
					</span>
        </a>
    </div>
    <div class="menuerright">
        <img src="{% static 'img/tephone.png' %}">
    </div>
</div>
<div class="homeslider">
    <div class="classfy">
        <!--<div class="classfyone">
            <p>
                <a href="#">钻石</a>
            </p>
            <div>
                <span><a href="#">30克</a></span>
                <span><a href="#">50克</a></span>
                <span><a href="#">80克</a></span>
                <span><a href="#">1克拉</a></span>
                <span><a href="#">异形钻</a></span>
            </div>
        </div>-->
    </div>
    <div class="picture">
        <p class="pp"><a href="{% url 'app:login' %}">免费注册</a></p>
        <form action="{% url 'app:onload' %}" method="post">
            {% csrf_token %}

            <dd class="uphone" id="uphone1">
                <p><input type="text" placeholder="11位数字" class="textone" name="uphone"></p>
                <div class="dd1">请填写您的手机号码
                    <div class="p_err">{{ p_err }}</div>
                </div>
            </dd>

            <input type="password" placeholder="6-20位必须包含数字字母" class="textfour" name="password">
            <div class="pas">
                <dd class="dd4">请输入密码 <p class="err1">{{ err }}</p></dd>
            </div>

            <p class="p1"><input type="checkbox" class="textsix"><span class="span3">自动登录</span><span
                    class="span4">忘记密码？</span></p>
            <p class="p2"><input type="submit" class="submit1" value="会员登录"></p>
        </form>

        <div class="phone"></div>

        <p class="p3">
            <img src="{% static 'img/Connect_logo_7.png' %}" class="img1">
            <img src="{% static 'img/wb.gif' %}" class="img2">
            <img src="{% static 'img/zfb.gif' %}" class="img3">
        </p>
    </div>


</div>
{#		<div id="bga" style="display: none;"></div>#}
{#		<div class="changea" style="display: none;">#}
{#		    <p class="pdeng">登录提示<span>×</span></p>#}
{#			<div class="changeoneea">#}
{#				<p class="num">18692372711,欢迎光临戴欧妮珠宝网</p>#}
{#			</div>#}
{#			<input type="button" value="确定">#}
{#		</div>#}


<div class="security">

</div>
<div class="footer">
    <div class="footerone">
        <div class="kuang kuanga">
            <i class="ione"></i>
            <ul>
                <li class="lii"> 购买支付</li>
                <li><a href="#">新手教程</a></li>
                <li><a href="#">订购流程</a></li>
                <li><a href="#">支付常见问题</a></li>
            </ul>
        </div>
        <div class="kuang">
            <i class="itwo"></i>
            <ul>
                <li class="lii"> 收获指南</li>
                <li><a href="#">订单处理时间</a></li>
                <li><a href="#">配送方法和收费</a></li>
                <li><a href="#">防伪包装</a></li>
            </ul>
        </div>
        <div class="kuang">
            <i class="ithree"></i>
            <ul>
                <li class="lii">售后服务</li>
                <li><a href="#">质量承诺</a></li>
                <li><a href="#">购物协议</a></li>
                <li><a href="#">售后服务</a></li>
            </ul>
        </div>
        <div class="kuang">
            <i class="ifour"></i>
            <ul>
                <li class="lii"> 会员中心</li>
                <li><a href="#">如何成为会员</a></li>
                <li><a href="#">积分规则</a></li>
                <li><a href="#">优惠政策</a></li>
            </ul>
        </div>
        <div class="kuang">
            <i class="ifive"></i>
            <ul>
                <li class="lii"> 关于戴欧妮</li>
                <li><a href="#">戴欧妮介绍</a></li>
                <li><a href="#">戴欧妮资质</a></li>
                <li><a href="#">戴欧妮优势</a></li>
            </ul>
        </div>
        <div class="kuang">
            <i class="isix"></i>
            <ul>
                <li class="lii"> 更多服务</li>
                <li><a href="#">鉴定机构</a></li>
                <li><a href="#">联系我们</a></li>
                <li><a href="#">网站地图</a></li>
            </ul>
        </div>
    </div>
    <div class="footertwo">
        <p>
					<span class="span1">
                                                                体验中心地址：广东省深圳市南山区创业路中兴工业城9栋601 联系电话：4006578478
					</span>
            <span class="span2">
						全球24小时服务热线
					</span>
        </p>
        <p class="p1">
					<span class="span1">
						Copyright @ 2007-2014 深圳市戴欧妮网络科技有限公司 ALL Rights Reserved 经营许可证编号：粤B2-20080371 粤ICP备11058956号-1
					</span>
            <span class="span3">
						4006-578-478
					</span>
        </p>
    </div>
    <div class="footerthree">
        <div class="onee">
            <div class="img">
                <img src="{% static 'img/icon1_03.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">网上交易</p>
                <p>保障中心</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon2_05.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">众信认证</p>
                <p>安全电商</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon3_03.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">工商网监</p>
                <p>电子信息</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon4_11.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">经营性网站</p>
                <p>备案信息</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon5_14.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">诚信电商</p>
                <p>信用认证</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon6_16.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">百度推广</p>
                <p>安全认证</p>
            </div>
        </div>
        <div class="one">
            <div class="img">
                <img src="{% static 'img/icon7_05.jpg' %}">
            </div>
            <div class="info">
                <p class="p1">戴欧妮珠宝</p>
                <p>荣誉证书</p>
            </div>
        </div>
    </div>
    <div class="footerfour">
        <p class="p1">
            友情链接：
            <a href="#">钻石&nbsp;&nbsp;&nbsp;</a> <a href="#">正佳养生网 &nbsp;&nbsp;&nbsp; </a><a href="#">中关村商城&nbsp;&nbsp;&nbsp;</a><a
                href="#">裸钻&nbsp;&nbsp;&nbsp;</a><a href="#">钻石珠宝论坛&nbsp;&nbsp;&nbsp;
        </a><a href="#">麻豆网&nbsp;&nbsp;&nbsp;</a>
            <a href="#">时尚生活网&nbsp;&nbsp;&nbsp; </a><a href="#"> 母亲节礼物&nbsp;&nbsp;&nbsp;</a><a href="#">中国美业网&nbsp;&nbsp;&nbsp;</a>
            <a href="#">婚戒 &nbsp;&nbsp;&nbsp;</a><a href="#">结婚 &nbsp;&nbsp;&nbsp; </a><a href="#">新疆和田玉&nbsp;&nbsp;&nbsp;</a><a
                href="#">手礼网&nbsp;&nbsp;&nbsp;</a>
            <a href="#">和田玉 &nbsp;&nbsp;&nbsp; </a><a href="#">国美在线优惠券 &nbsp;&nbsp;&nbsp;</a><a href="#">钻戒网&nbsp;&nbsp;&nbsp;</a><a
                href="#">服装搭配&nbsp;&nbsp;&nbsp;</a>

        </p>
        <p class="p2">友情链接请加QQ:2992936048</p>
    </div>
</div>
<div class="Zxs">


</div>
</body>
</html>