DON/DON/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app'))
]

DON/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.index,name='index'), # 首页
    url(r'^login/$',views.login,name='login'), # 注册
    url(r'^outlogin/$',views.outlogin,name='outlogin'), # 退出登录
    url(r'^onload/$',views.onload,name='onload'), # 登录
    url(r'^shoplist/$',views.shoplist,name='shoplist'), # 商品展示
    url(r'^shopinfo/(\d+)/$',views.shopinfo,name='shopinfo'), # 商品详情页
    url(r'^MyCar/$',views.MyCar,name='MyCar'), # 购物车
    url(r'^addCar/$',views.addCar,name='addCar'), # 添加购物车
    url(r'^subCar/$',views.subCar,name='subCar'), # 删除购物车
    url(r'^statusCar/$',views.statusCar,name='statusCar'), #
    url(r'^isallCar/$',views.isallCar,name='isallCar'),
    url(r'^addshop/$',views.addshop,name='addshop'),
    url(r'^subshop/$',views.subshop,name='subshop'),
    url(r'^checkphone/$',views.checkphone,name='checkphone'),
    url(r'^removeshop/$',views.removeshop,name='removeshop'),
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    url(r'^orderdetail/(\d+)/$',views.orderdetail,name='orderdetail'),
    url(r'^orderlist/(\d+)/$',views.orderlist,name='orderlist'),
]

DON/app/models.py
from django.db import models


class lunbotu(models.Model):
    data = models.CharField(max_length=256)
    name = models.IntegerField()


class User(models.Model):
    uphone = models.CharField(max_length=100, unique=True)
    uname = models.CharField(max_length=100)
    password = models.CharField(max_length=255)
    token = models.CharField(max_length=255)


class Shoplist(models.Model):
    src = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    content1 = models.CharField(max_length=255)
    content2 = models.CharField(max_length=255)


class Cart(models.Model):
    user = models.ForeignKey(User)
    shoplist = models.ForeignKey(Shoplist)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0)
    idenrifier = models.CharField(max_length=255)


class OrderShop(models.Model):
    order = models.ForeignKey(Order)
    shoplist = models.ForeignKey(Shoplist)
    number = models.IntegerField()

DON/templates/order/orderdetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/orderdetail.css' %}">
    <script type="text/javascript " href="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
<div>
    <table class="table table-hover">'
        <tr class="ordertop">
            <td>订单号:{{ order.idenrifier }}</td>
            <td>商品名称</td>
            <td>商品数量</td>
            <td>商品单价</td>
        </tr>
        {% for ordershops in order.ordershop_set.all %}
        <tr class="orderall">
                <td class="orderimg"><img src="{{ ordershops.shoplist.src }}" alt=""></td>
                <td class="ordername">{{ ordershops.shoplist.name }}</td>
                <td class="ordernumber">x{{ ordershops.number }}</td>
                <td class="orderprice">{{ ordershops.shoplist.content2 }}元</td>
        </tr>
        {% endfor %}
        <tr class="orderfoot">
            <td></td>
            <td></td>
            <td></td>
            <td class="orderpay">
                {% if order.status == 0 %}
                    <div class="paythis">付款</div>
                {% endif %}
            </td>
        </tr>
    </table>
</div>

</body>
</html>

DON/templates/order/orderlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/orderlist.css' %}">
    <script type="text/javascript " href="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
    <table class="table table-hover">
        <tr class="ordertop">
            <td style="color: white;background: #6d6c6c">订单号</td>
        </tr>
        {% for order in orders %}
            <tr>
            <td>

                    <a href="{% url 'app:orderdetail' order.idenrifier %}">
                    {{ forloop.counter }}丶{{ order.idenrifier }}
                        <span style="color: white;background: red">
                            {% if order.status == 0 %}
                                未付款
                            {% elif order.status == 1 %}
                                已付款(未发货)
                            {% elif order.status == 2 %}
                                已签收
                            {% endif %}
                        </span>
                    </a>

            </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>